version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: webapp
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    command:  python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-api-service
    environment:
        RABBITMQ_DEFAULT_USER: rabbitMQ
        RABBITMQ_DEFAULT_PASS: rabbit
    ports:
        - 5672:5672
        - 15672:15672

  celery:
    build: .
    restart: always
    command: bash -c "cd /code/ && rm -rf celerybeat.pid && celery -A api_service worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq