# Generated by Django 4.0.4 on 2022-05-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('pre', 'preplay'), ('in', 'inplay')], max_length=3)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('s', 'Started'), ('e', 'Ended'), ('c', 'Cancelled')], max_length=1)),
                ('scheduled_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport')),
            ],
        ),
    ]
